[[session]]
name = "Home"
path = "/home/asim"
startup_command = "ls"
windows = [ "helix", "yazi" ]

[[session]]
name = "Downloads"
path = "~/Downloads"
startup_command = "yazi"

[[window]]
name = "helix"
startup_script = "helix ~/Files/todo.md"

[[window]]
name = "yazi"
startup_script = "yazi"
