[general]
import = [
        "~/.config/alacritty/high-contrast.toml"
    ]
live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
style = {shape = "Beam",blinking = "On"}
# custom_cursor_colors = true

[mouse]
hide_when_typing = true
[keyboard]
bindings = [{ key = "n",mods = "Control",action= "CreateNewWindow" }]
[env]
TERM = "alacritty"

[font]
size = 11.2

[font.normal]
family = "JetBrainsMono Nerd Font Mono"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
decorations = "Full"
dynamic_padding = true
opacity = 0.8
startup_mode = "Windowed"
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

# [window.dimensions]
# columns = 160
# lines = 45

[window.padding]
x = 0
y = 0
