[general]
import = [
        "~/.config/alacritty/everforest_dark.toml"
    ]
live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
style = {shape = "Beam",blinking = "On"}
# custom_cursor_colors = true

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
        { key = "v", mods = "Control", action = "Paste"},
        { key = "Enter",mods = "Super",action = "CreateNewWindow" }
   ]

[env]
TERM = "alacritty"

[font]
size = 15 

[font.normal]
family = "JetBrainsMono Nerd Font"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
dynamic_title = true
decorations = "None"
dynamic_padding = true
opacity = 1
startup_mode = "Windowed"

[window.padding]
x = 0
y = 0
