# theme = "doom_acario_dark"
# theme = "ayu_evolve"
# theme = "material_deep_ocean"
theme = "jetbrains_dark" 
[editor]
line-number = "absolute"
bufferline = "multiple"
mouse = false
scroll-lines = 1
cursorline = true
auto-save = false
completion-trigger-len = 1
true-color = true
color-modes = true
auto-pairs = true
rulers = [100]
idle-timeout = 50
[editor.indent-guides]
render = true
character = "▏"

[editor.soft-wrap]
enable = true
max-wrap = 80 # increase value to reduce forced mid-word wrapping
max-indent-retain = 0
wrap-indicator = ""  # set wrap-indicator to "↪" to have a symbol.

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.statusline]
left = ["mode",  "file-name", "read-only-indicator", "total-line-numbers", "file-encoding"]
center = [ "spinner"]
right = ["primary-selection-length", "position", "position-percentage", "spacer", "diagnostics", "workspace-diagnostics", "version-control"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
A-tab = "goto_next_buffer"
A-S-tab = "goto_previous_buffer"
tab = "move_parent_node_end"
S-tab = "move_parent_node_start"
S-space = "flip_selections"
y = "yank_to_clipboard"
p = "paste_clipboard_before"
C-p = "paste_clipboard_after"
S-x = "extend_line_up"
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]

[keys.normal.space]
i = "command_mode"
e = [":new", ":insert-output lf-pick", "select_all", "split_selection_on_newline", "goto_file", "goto_last_modified_file", ":buffer-close!", ":redraw"]
space = "flip_selections"
w = ":w"
q = ":q"
f = "file_picker"
h = "file_picker_in_current_buffer_directory"
F = "file_picker_in_current_directory"
x = ":buffer-close"

# [keys.normal.g]
# x = ":buffer-close"

[keys.insert]
A-tab = "goto_next_buffer"
A-S-tab = "goto_previous_buffer"
C-h = "move_char_left" 
C-l = "move_char_right" 

[keys.select]
tab = "extend_parent_node_end"
A-tab = "goto_next_buffer"
A-S-tab = "goto_previous_buffer"
y = "yank_to_clipboard"
p = "paste_clipboard_before"
# S-tab = "extend_parent_node_start"
# esc = 

[keys.select.space]
w = ":w"
q = ":q"
i = "command_mode"
h = "file_picker_in_current_buffer_directory"
f = "file_picker"






# to have key map (S-f) working follow these
## touch ~/.local/bin/lf-pick
# chmod +x ~/.local/bin/lf-pick
# or add that lf-pick file to any (echo $PATH) output directory

# function lfp(){
#   local TEMP=$(mktemp)
#   lf -selection-path=$TEMP
#   cat $TEMP
# }

# lfp
# or
# function lfp(){
#   local TEMP=$(mktemp)
#   lf -selection-path=$TEMP
#   echo >> $TEMP
#   while read -r line
#   do
#     echo "$line"
#   done < "$TEMP"
# }

# lfp
