#### i do these with pyprland now ###
# windowrule= float,title:^(tty-clock)$
# windowrule= size 320 140,title:^(tty-clock)$
# windowrule= float,title:^(btop)$
# windowrule= size 1000 650,title:^(btop)$
# windowrulev2 = noborder, onworkspace:w[1]

# Picture in Picture, to have the numbers for size and position, place and size windows as you 
# prefer and then in a terminal run "hyprctl clients" and note down those numbers and insert them
# here.
# Picture in Picture, to have the numbers for size and position, place and size windows as you 
# like
windowrule = float on, pin on, move (990) (15), size 930 520, match:title ^(Picture-in-Picture)$
windowrule = float on, pin on, move (990) (15), size 930 520, match:title ^(Picture in picture)$

windowrule = float on, match:class (mpv)
windowrule = float on, move (0) (0), match:class (feh)
# windowrule v2 to idle-inhibit when anything is full screened
windowrule = idle_inhibit fullscreen, match:class ^(*)$
windowrule = idle_inhibit fullscreen, match:title ^(*)$
windowrule = idle_inhibit fullscreen, match:fullscreen 1
windowrule = float on, match:class (anki)
windowrule = float on, move (935) (0), match:class (MuPDF)
windowrule = float on, size 1622 982, move (149) (36), match:class (org.kde.okular)
windowrule = float on, size 1300 650, move (350) (140), match:class ([Tt]hunar)
windowrule = float on, size 783 560, move (1136) (487), match:class (org.twosheds.iwgtk)
windowrule = float on, size 783 560, move (1136) (487), match:class (iwgtk)
windowrule = float on, size 783 560, move (1136) (487), match:class (bluetuith)
windowrule = float on, size 783 560, move (1136) (487), match:class (org.pulseaudio.pavucontrol)
windowrule = float on, size 961 561, move (959) (493), match:class (galculator)
# windowrulev2 = float, class:(virt-manager)
windowrule = size 1300 650, move (350) (140), match:class (virt-manager)
# size for windows to have consistent window size in psuedo mode
windowrule = size 1426 900, match:class (Alacritty)
# windowrulev2 = size 1750 1020, initialTitle:(Zen Browser)
# Picture in Picture, to have the numbers for size and position, place and size windows as you 
# Common modals
windowrule = float on, size 1111 333, move (404) (373), match:title (Opening)(.*)
windowrule = float on, move (503) (216), size 914 647, match:title ^(File Upload)$
windowrule = float on, move (503) (216), size 914 647, match:title ^(Open)(.*)
windowrule = float on, move (503) (216), size 914 647, match:title ^(Open)$
windowrule = float on, move (503) (216), size 914 647, match:title ^(Choose Files)$
windowrule = float on, move (503) (216), size 914 647, match:title ^(Save As)$
windowrule = float on, move (503) (216), size 914 647, match:title ^(Confirm to replace files)$
windowrule = float on, move (503) (216), size 914 647, match:title ^(File Operation Progress)$
windowrule = float on, move (503) (216), size 914 647, match:class ^(xdg-desktop-portal-gtk)$
